### ISSUE TITLE
automatic conversion from Tex to HTML and PDF

### ISSUE THREAD

**Issue by FrederikBornemann** [FrederikBornemann/causalmlbooktest.github.io#1]
## TODO:

- [ ] **add workflow to create pdf from tex file**
   - use [pandoc](https://pandoc.org/) to convert tex into pdf. For instructions to use pandoc in github actions see [here](https://github.com/pandoc/pandoc-action-example)
 ---
- [ ] **add workflow to create HTML from tex file**
 - use [pandoc](https://pandoc.org/)
 - create a custom html template (header, footer) for pandoc. See [here](https://pandoc.org/MANUAL.html#templates)
   - load template on the actions server (?) `~/.pandoc/templates/default.html`
 - add the template to the pandoc args ([link](https://pandoc.org/MANUAL.html#option--template))
---
- [ ] **modify conversion to export individual chapters**
---
- [ ] **modify conversion for correct formatting (mathml, [kaobook](https://github.com/fmarotta/kaobook))**
---
- [ ] **run actions when new version of the book is published**

**Comment by FrederikBornemann** [comment]
## [Unbuch](https://github.com/mrtzh/unbuch)
A simple pandoc setup to compile a book from markdown sources into html pages and pdf.

Features:

- Tufte-inspired layout with sidenotes
- Latex formulas via katex plugin
- Custom Environments
- Cross references
- HTML pages, individual PDF chapters, PDF book
